before_commands:
    - "composer install"

checks:
    php: true

build:
    environment:
        php: '7.0.6'
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'clover'
